import "@ant-design/v5-patch-for-react-19";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import RebalanceBus from "../components/RebalanceBus";
import NavBar from "../components/NavBar"; // ✅ 추가

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata = { title: "Create Next App", description: "Generated by create next app" };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <RebalanceBus />
        <NavBar /> {/* ✅ 여기서 전 페이지 공통으로 보여줌 */}
        {children}
      </body>
    </html>
  );
}
